// build.mjs
// Turns the Tokens Studio files in /tokens into dist/tokens.css.
//
// How it works, in plain terms:
// 1. Read tokens/$themes.json, the file Tokens Studio writes when you
//    create Themes. Find the "Color mode" group and its Light and Dark themes.
// 2. Ask Style Dictionary to resolve each theme separately.
// 3. Write one CSS file: primitives as private variables (--_color-...),
//    semantic tokens as light-dark(<light value>, <dark value>).

import { readFile, mkdir, writeFile } from 'node:fs/promises';
import StyleDictionary from 'style-dictionary';
import { register } from '@tokens-studio/sd-transforms';

// ---- Settings you might change ---------------------------------------
const TOKENS_DIR = 'tokens';
const OUTPUT_FILE = 'dist/tokens.css';
const MODE_GROUP = 'Color mode'; // Theme group name in Tokens Studio
const LIGHT_THEME = 'Light'; // Theme names inside that group
const DARK_THEME = 'Dark';
const PRIVATE_PREFIX = '_'; // Primitives become --_color-gray-900
// ----------------------------------------------------------------------

register(StyleDictionary);

const themes = JSON.parse(
  await readFile(`${TOKENS_DIR}/$themes.json`, 'utf-8'),
);

const findTheme = (name) => {
  const theme = themes.find((t) => t.group === MODE_GROUP && t.name === name);
  if (!theme) {
    throw new Error(
      `Could not find the "${name}" theme in the "${MODE_GROUP}" group. ` +
        'Check the theme names in Tokens Studio (Manage themes).',
    );
  }
  return theme;
};

// Which token sets does a theme use? "enabled" and "source" both count.
// "source" sets (the primitives) are available for references.
const setsFor = (theme) =>
  Object.entries(theme.selectedTokenSets)
    .filter(([, status]) => status !== 'disabled')
    .map(([set]) => set);

// Resolve every token for one theme with Style Dictionary.
async function resolveTheme(theme) {
  const sets = setsFor(theme);
  const sd = new StyleDictionary({
    source: sets.map((set) => `${TOKENS_DIR}/${set}.json`),
    preprocessors: ['tokens-studio'],
    log: { verbosity: 'silent' },
    platforms: {
      css: {
        transformGroup: 'tokens-studio',
        transforms: ['name/kebab'],
      },
    },
  });
  const { allTokens } = await sd.getPlatformTokens('css');

  // Remember which tokens came from "source" sets (primitives)
  const sourceSets = Object.entries(theme.selectedTokenSets)
    .filter(([, status]) => status === 'source')
    .map(([set]) => `${TOKENS_DIR}/${set}.json`);

  return allTokens.map((token) => ({
    ...token,
    isPrimitive: sourceSets.some((file) => token.filePath.endsWith(file)),
  }));
}

const light = await resolveTheme(findTheme(LIGHT_THEME));
const dark = await resolveTheme(findTheme(DARK_THEME));

const cssName = (token) =>
  `--${token.isPrimitive ? PRIVATE_PREFIX : ''}${token.name}`;

// Turn "{color.gray.900}" into "var(--_color-gray-900)".
// Anything that isn't a reference stays as its resolved value.
function cssValue(token, tokenList) {
  const raw = token.original.$value ?? token.original.value;
  const isReference =
    typeof raw === 'string' && /^\{[^}]+\}$/.test(raw.trim());
  if (!isReference) return token.$value ?? token.value;

  const path = raw.trim().slice(1, -1);
  const target = tokenList.find((t) => t.path.join('.') === path);
  if (!target) throw new Error(`${token.path.join('.')} points to missing token {${path}}`);
  return `var(${cssName(target)})`;
}

// Primitives (same in both themes)
const primitives = light.filter((t) => t.isPrimitive);

// Semantic tokens: pair each light token with its dark twin by name
const semanticLight = light.filter((t) => !t.isPrimitive);
const semanticDark = new Map(
  dark.filter((t) => !t.isPrimitive).map((t) => [t.name, t]),
);

const problems = [];
const semanticLines = semanticLight.map((lt) => {
  const dt = semanticDark.get(lt.name);
  if (!dt) {
    problems.push(`"${lt.path.join('.')}" has a Light value but no Dark value`);
    return '';
  }
  semanticDark.delete(lt.name);
  const lv = cssValue(lt, light);
  const dv = cssValue(dt, dark);
  const value = lv === dv ? lv : `light-dark(${lv}, ${dv})`;
  const comment = lt.$description ? ` /* ${lt.$description} */` : '';
  return `  ${cssName(lt)}: ${value};${comment}`;
});
for (const leftover of semanticDark.values()) {
  problems.push(`"${leftover.path.join('.')}" has a Dark value but no Light value`);
}
if (problems.length) {
  console.error('\nToken build stopped. Every semantic token needs both modes:\n');
  problems.forEach((p) => console.error(`  - ${p}`));
  console.error('');
  process.exit(1);
}

const css = `/**
 * Generated by build.mjs from the files in /${TOKENS_DIR}.
 * Do not edit by hand. Change tokens in Tokens Studio instead.
 */

:root {
  color-scheme: light dark;

  /* Primitives (private: do not use in components) */
${primitives.map((t) => `  ${cssName(t)}: ${cssValue(t, light)};`).join('\n')}

  /* Semantic: light-dark(light value, dark value) */
${semanticLines.join('\n')}
}

/* Optional manual override: <html data-theme="dark"> */
[data-theme="light"] { color-scheme: light; }
[data-theme="dark"]  { color-scheme: dark; }
`;

await mkdir('dist', { recursive: true });
await writeFile(OUTPUT_FILE, css);
console.log(
  `Built ${OUTPUT_FILE}: ${primitives.length} primitives, ${semanticLines.length} semantic tokens.`,
);
